// Generates the design-sync barrel entry + componentSrcMap for the admin UI.
//
// Quire Ink is an application, not a published component package: there is no library
// `dist/`, no shipped `.d.ts` tree, and `node_modules/quireink` does not exist. The
// converter therefore needs an explicit `--entry`, and with no `.d.ts` to enumerate from,
// an explicit `componentSrcMap` is the only thing that makes the component list real.
// Both are generated here rather than hand-typed so they cannot drift from the source.
//
// Run: node .design-sync/gen-entry.mjs
import { readdirSync, writeFileSync, readFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'
import { Project, Node, ts } from '../.ds-sync/node_modules/ts-morph/dist/ts-morph.js'

const ROOT = resolve(import.meta.dirname, '..')

// `src/admin/pages` is DELIBERATELY absent.
//
// The thirteen route screens are not design surface, they are routes: each one fetches its
// own data on mount through `@/admin/api`, so outside a running server it renders a red
// `HTTP 404` box. That is worse than shipping no card at all — the render check counts it as
// "rendered", and the design agent learns a failure state as if it were the component's look.
// No prop can fix it either, because the fetch is internal.
//
// Whatever these screens are made OF is already synced: PageHeader, the tables, the settings
// panels, the stat tiles. To bring the screens themselves back, add the directory here and
// stub the API at bundle-build time first.
const DIRS = ['src/admin/ui', 'src/admin/components', 'src/admin']

// Not components, and each one would otherwise ship a meaningless card:
//  - help-kit is inline markup glue for the Help page (`A`, `C`, `P`, `UL`, …)
//  - App/state are the SPA's own mount plumbing, not design surface
const SKIP_FILES = new Set(['help-kit.tsx', 'App.tsx', 'state.tsx'])
// Exported for the provider chain and for `Link`, but never a preview card.
const NON_CARD = new Set([
  'ThemeProvider', 'ToastProvider', 'AdminI18nProvider', 'RouterProvider',
])
// PascalCase, and the initializer is a call — so they read as components to the scan below —
// but `Image.extend({…})` and `Node.create({…})` build Tiptap schema nodes, not React
// elements. Putting them on the namespace fails the bundle's own export smoke check.
const NOT_COMPONENTS = new Set(['CaptionedImage', 'Video'])

const project = new Project({
  skipAddingFilesFromTsConfig: true,
  compilerOptions: { jsx: ts.JsxEmit.Preserve, allowJs: true, skipLibCheck: true },
})

/** A PascalCase export whose declaration is a function/class — i.e. renderable. */
function componentExports(file) {
  const sf = project.addSourceFileAtPath(file)
  const out = []
  for (const [exportedAs, decls] of sf.getExportedDeclarations()) {
    // Every page is `export default function Analytics()`, so the useful name lives on the
    // declaration, not the export key. Recover it and remember it needs `default as`.
    const name = exportedAs === 'default'
      ? decls.map((d) => d.getName?.()).find((n) => n && n !== 'default')
      : exportedAs
    if (!name) continue
    if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) continue // drops CARD_X, SETTING_LABEL, …
    const renderable = decls.some((d) => {
      if (Node.isFunctionDeclaration(d) || Node.isClassDeclaration(d)) return true
      if (Node.isVariableDeclaration(d)) {
        const init = d.getInitializer()
        if (!init) return false
        // `const X = 'utility classes'` is a token constant, not a component.
        if (Node.isStringLiteral(init) || Node.isNoSubstitutionTemplateLiteral(init)) return false
        if (Node.isTemplateExpression(init)) return false
        return true
      }
      return false
    })
    if (renderable) out.push({ name, isDefault: exportedAs === 'default' })
  }
  return out.sort((a, b) => a.name.localeCompare(b.name))
}

const files = []
for (const dir of DIRS) {
  for (const f of readdirSync(join(ROOT, dir))) {
    if (!f.endsWith('.tsx') || f.includes('.test.')) continue
    if (SKIP_FILES.has(f)) continue
    files.push(join(ROOT, dir, f))
  }
}

const byFile = new Map()
const srcMap = {}
const seen = new Map()
for (const file of files.sort()) {
  const names = componentExports(file).filter(({ name }) => {
    if (NOT_COMPONENTS.has(name)) return false
    const prev = seen.get(name)
    if (prev) { console.error(`  ! duplicate export ${name}: keeping ${relative(ROOT, prev)}`); return false }
    seen.set(name, file)
    return true
  })
  if (!names.length) continue
  byFile.set(file, names)
  for (const { name } of names) srcMap[name] = relative(ROOT, file).replace(/\\/g, '/')
}

const lines = [
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.',
  '// The design-sync bundle entry: every admin component, re-exported from its real source.',
  '// This is a barrel over the shipped code, never a reimplementation.',
  '',
]
for (const [file, names] of byFile) {
  let spec = relative(join(ROOT, '.design-sync'), file).replace(/\\/g, '/')
  if (!spec.startsWith('.')) spec = './' + spec
  const clause = names.map(({ name, isDefault }) => (isDefault ? `default as ${name}` : name)).join(', ')
  lines.push(`export { ${clause} } from '${spec}'`)
}
writeFileSync(join(ROOT, '.design-sync/entry.tsx'), lines.join('\n') + '\n')

const cfgPath = join(ROOT, '.design-sync/config.json')
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'))
cfg.componentSrcMap = { ...srcMap, ...Object.fromEntries([...NON_CARD].map((n) => [n, srcMap[n] ?? null])) }
writeFileSync(cfgPath, JSON.stringify(cfg, null, 2) + '\n')

console.error(`entry: ${byFile.size} files, ${Object.keys(srcMap).length} components`)
console.error(Object.keys(srcMap).join(' '))
