// Emits the two stylesheets the design-sync bundle needs but the repo never writes to disk.
//
// The admin gets its tokens and its @font-face rules from `adminStyles()` in
// `src/web/admin/spa.ts`, which builds them at request time from the owner's saved settings
// and inlines them into the shell. A design-sync preview has no server and no owner, so
// those rules simply are not there: components render with no type scale, no palette and no
// brand font. Rather than restate any of it, this calls the SAME functions the shell calls,
// against DEFAULT_SETTINGS, and writes the result out. The CSS is the product's own.
//
// Run: bun .design-sync/gen-styles.ts   (regenerate whenever themes/typography change)
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { DEFAULT_SETTINGS, typographyToCss, fontToCss } from '@/content/settings'
import { themesToCss, fontPresetCss, chromeFontCss, THEME_PRESETS } from '@/content/themes'
import { allFontFaceCss, MONO_TRACKING } from '@/render/font-faces'

const OUT = new URL('./generated/', import.meta.url)
mkdirSync(OUT, { recursive: true })

const s = DEFAULT_SETTINGS

// ── tokens.css — everything adminStyles() injects EXCEPT the @font-face block.
// Order is copied from adminStyles: palettes, then type scale, then reading preset, then any
// uploaded face, then the chrome font last so it has the final word on --font-sans.
const tokens = [
  '/* GENERATED by .design-sync/gen-styles.ts from DEFAULT_SETTINGS — do not edit by hand. */',
  `:root{--font-sans:'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif;`
  + `--font-reading:var(--font-sans);`
  + `--font-mono:'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace}`,
  `body{font-family:var(--font-sans), system-ui, -apple-system, 'Segoe UI', sans-serif}`,
  themesToCss(s.themes, s.themePreset),
  typographyToCss(s.typography),
  fontPresetCss(s.fontPreset),
  fontToCss(s.customFont),
  chromeFontCss(s.chromeFont),
  MONO_TRACKING,
].filter(Boolean).join('\n')
writeFileSync(new URL('tokens.css', OUT), tokens + '\n')

// ── fonts.css — the same @font-face rules, repointed at the files on disk.
// `allFontFaceCss()` writes `url('/fonts/<slug>-<subset>.woff2')`, which is the route the
// server exposes; the converter needs a path it can resolve and copy, so rewrite the one
// prefix and leave every other byte (weights, unicode-range) untouched.
const fonts = allFontFaceCss().replace(
  /url\('\/fonts\//g,
  "url('../../src/assets/static/fonts/",
)
writeFileSync(
  new URL('fonts.css', OUT),
  '/* GENERATED by .design-sync/gen-styles.ts — do not edit by hand. */\n' + fonts + '\n',
)

// ── admin.css — the compiled Tailwind sheet with the tokens appended.
//
// This concatenation is the `cssEntry` the converter ships as `_ds_bundle.css`, and it is a
// concatenation rather than an `@import` because only ONE file is copied: an import would
// point at a tokens.css that never reaches the bundle. The order matches the real shell,
// where `<link admin.css>` is followed by the inline `<style>` block, so the runtime tokens
// still get the last word on anything they both set.
const compiled = readFileSync('src/admin/dist/admin.css', 'utf8')
writeFileSync(new URL('admin.css', OUT), `${compiled}\n${tokens}\n`)

// ── settings.json — DEFAULT_SETTINGS as plain data for the preview files.
//
// A preview cannot `import { DEFAULT_SETTINGS } from '@/content/settings'`: that module
// reaches `sharp`, which reaches `detect-libc`, which requires `child_process`, and the
// preview bundle is browser code. Serialising it here keeps the previews on the product's
// real defaults without dragging the server graph into the browser.
writeFileSync(new URL('settings.json', OUT), JSON.stringify(s, null, 2) + '\n')

// The palette list the theme editor renders, from the same module the admin reads it from.
writeFileSync(new URL('presets.json', OUT), JSON.stringify(THEME_PRESETS, null, 2) + '\n')

const faces = (fonts.match(/@font-face/g) ?? []).length
console.log(`tokens.css: ${tokens.length} bytes`)
console.log(`fonts.css: ${faces} @font-face rules`)
console.log(`admin.css: ${((compiled.length + tokens.length) / 1024).toFixed(0)} KB (compiled + tokens)`)
