// Emits the READING site's stylesheet as static files, for the tokens-only design system.
//
// The public site has no React components at all — every page is built as an escaped HTML
// string in `.ts`, and its CSS lives in TypeScript constants. So there is nothing to export
// as a component library, and hand-writing React lookalikes would be a reimplementation that
// rots on the first change to `front-card.ts`. What CAN be exported honestly is the look:
// the real palette, type scale, prose rules and self-hosted faces.
//
// Both halves come from the product itself, in the order the document uses them:
// `renderDocument` links PUBLIC_CSS immediately before the inline `pageStyles` block, so the
// cascade here reads exactly as it does on quireink.com.
//
// Run: bun .design-sync/gen-reader.ts
import { mkdirSync, writeFileSync } from 'node:fs'
import { DEFAULT_SETTINGS } from '@/content/settings'
import { pageStyles } from '@/web/layout'
import { PUBLIC_CSS } from '@/web/public.css'
import { allFontFaceCss } from '@/render/font-faces'

const OUT = new URL('./generated/', import.meta.url)
mkdirSync(OUT, { recursive: true })

const composed = `${PUBLIC_CSS}\n${pageStyles(DEFAULT_SETTINGS)}`

// The @font-face rules are pulled OUT and repointed. `pageStyles` writes them with the
// server route (`url('/fonts/…')`), which resolves to nothing in a design bundle; the
// converter needs a path it can follow and copy. Everything else is left byte-for-byte.
const FACE_RX = /@font-face\{[^}]*\}/g
const body = composed.replace(FACE_RX, '').replace(/\n{3,}/g, '\n\n')
writeFileSync(
  new URL('reader.css', OUT),
  '/* GENERATED by .design-sync/gen-reader.ts from DEFAULT_SETTINGS - do not edit by hand. */\n'
  + body + '\n',
)

// Every family, not just the two the default preset activates: an agent designing with this
// system may reach for Literata or IBM Plex Mono, and a declaration costs nothing until a
// glyph actually needs it (that is what the unicode-range slicing is for).
const fonts = allFontFaceCss().replace(/url\('\/fonts\//g, "url('../../src/assets/static/fonts/")
writeFileSync(
  new URL('reader-fonts.css', OUT),
  '/* GENERATED by .design-sync/gen-reader.ts - do not edit by hand. */\n' + fonts + '\n',
)

const tokens = new Set([...body.matchAll(/--[a-z][a-z0-9-]*(?=\s*:)/g)].map((m) => m[0]))
console.log(`reader.css: ${(body.length / 1024).toFixed(0)} KB, ${tokens.size} custom properties`)
console.log(`reader-fonts.css: ${(fonts.match(/@font-face/g) ?? []).length} @font-face rules`)
console.log(`stripped ${(composed.match(FACE_RX) ?? []).length} inline face rule(s) from the sheet`)
