// GENERATED by `bun scripts/gen-shiki-langs.ts` from Shiki 4.4.3. Do not edit by hand:
// `shiki-langs.test.ts` fails the day this and Shiki's own table disagree, and names the script.
//
// Every spelling a fence may use, mapped to the ONE id its grammar is filed under. A copy rather
// than an import because the import carried every grammar with it into the Cloudflare build; the
// reason is at the top of the script.

/** Every grammar id (242). */
const IDS =
  'abap actionscript-3 ada ahk ahk2 angular-html angular-ts apache apex apl applescript ara ' +
  'asciidoc asm astro awk ballerina bat beancount berry bibtex bicep bird2 blade bsl c c3 ' +
  'cadence cairo chapel clarity clojure cmake cobol codeowners codeql coffee common-lisp coq ' +
  'cpp crystal csharp css csv cue cypher d dart dax desktop diff docker dotenv dream-maker edge ' +
  'elixir elm emacs-lisp erb erlang fennel fish fluent fortran-fixed-form fortran-free-form ' +
  'fsharp gdresource gdscript gdshader genie gherkin git-commit git-rebase gleam glimmer-js ' +
  'glimmer-ts glsl gn gnuplot go graphql groovy hack haml handlebars haskell haxe hcl hjson ' +
  'hlsl html html-derivative http hurl hxml hy imba ini java javascript jinja jison json json5 ' +
  'jsonc jsonl jsonnet jssm jsx julia just kdl kotlin kusto latex lean less liquid llvm log ' +
  'logo lua luau make markdown marko matlab mdc mdx mermaid mipsasm mojo moonbit move narrat ' +
  'nextflow nextflow-groovy nginx nim nix nsis nushell objective-c objective-cpp ocaml odin ' +
  'openscad org pascal perl php pkl plsql po polar postcss powerquery powershell prisma prolog ' +
  'proto pug puppet purescript python qml qmldir qss r racket raku razor rbs reg regexp rel ' +
  'riscv ron rosmsg rst ruby rust sas sass scala scheme scss sdbl shaderlab shellscript ' +
  'shellsession smalltalk smithy solidity soy sparql splunk sql ssh-config stata stylus ' +
  'surrealql svelte swift system-verilog systemd talonscript tasl tcl templ terraform tex toml ' +
  'ts-tags tsv tsx turtle twig typescript typespec typst v vala vb verilog vhdl viml vue ' +
  'vue-html vue-vine vyper wasm wenyan wgsl wikitext wit wolfram xml xsl yaml zenscript zig'

/** Every other spelling, `alias=id` (104). */
const ALIASES =
  '1c-query=sdbl 1c=bsl actionscript=actionscript-3 adoc=asciidoc ahk1=ahk as3=actionscript-3 ' +
  'bash=shellscript batch=bat be=berry bird=bird2 c#=csharp c++=cpp cdc=cadence chpl=chapel ' +
  'cjs=javascript clj=clojure closure-templates=soy cmd=bat coffeescript=coffee ' +
  'console=shellsession cql=cypher cs=csharp cts=typescript dockerfile=docker elisp=emacs-lisp ' +
  'erl=erlang f#=fsharp f03=fortran-free-form f08=fortran-free-form f18=fortran-free-form ' +
  'f77=fortran-fixed-form f90=fortran-free-form f95=fortran-free-form f=fortran-fixed-form ' +
  'for=fortran-fixed-form fs=fsharp fsl=jssm ftl=fluent gd=gdscript gjs=glimmer-js gql=graphql ' +
  'gts=glimmer-ts hbs=handlebars hs=haskell jade=pug jl=julia js=javascript justfile=just ' +
  'kql=kusto kt=kotlin kts=kotlin lean4=lean lisp=common-lisp lit=ts-tags makefile=make ' +
  'mbt=moonbit mbti=moonbit md=markdown mediawiki=wikitext mips=mipsasm mjs=javascript ' +
  'mmd=mermaid mts=typescript nar=narrat nf=nextflow nu=nushell objc=objective-c perl6=raku ' +
  'pot=po potx=po properties=ini protobuf=proto ps1=powershell ps=powershell pwsh=powershell ' +
  'py=python ql=codeql rb=ruby regex=regexp rs=rust ruby-signature=rbs scad=openscad ' +
  'sh=shellscript shader=shaderlab shell=shellscript spl=splunk styl=stylus surql=surrealql ' +
  'talon=talonscript tf=terraform tfvars=terraform tres=gdresource ts=typescript ' +
  'tscn=gdresource tsp=typespec typ=typst vim=viml vimscript=viml vy=vyper wiki=wikitext ' +
  'wl=wolfram yml=yaml zsh=shellscript 文言=wenyan'

/** Shiki's spellings, ids and aliases alike, to the id their grammar is filed under. */
export const SHIKI_LANGS: ReadonlyMap<string, string> = new Map([
  ...IDS.split(' ').map((id): [string, string] => [id, id]),
  ...ALIASES.split(' ').map((pair): [string, string] => {
    const at = pair.indexOf('=')
    return [pair.slice(0, at), pair.slice(at + 1)]
  }),
])
