// `bun scripts/gen-shiki-langs.ts` — writes `src/render/shiki-langs.ts`, Shiki's own table of
// languages and the spellings each answers to, as plain data.
//
// WHY A COPY, when `highlight.ts` used to read the table straight out of `shiki`. Reading it meant
// importing the bundle that holds it, and that bundle names every grammar Shiki ships behind a
// dynamic import. Bun follows those; so does its bundler. The Cloudflare build has no code
// splitting, so the 346 dynamic imports became 7.8 MB of grammars inside `worker.js`, parsed by
// every isolate that ever started, to answer one question — "is `sh` a language?" — whose answer
// is 4 KB of text. Measured 2026-10-03: 16.14 MB of worker, of which Shiki's grammars were the
// largest single part.
//
// The copy cannot drift without saying so: `src/render/shiki-langs.test.ts` rebuilds the table from
// Shiki the way `highlight.ts` used to and fails on any difference, naming this script. So a Shiki
// upgrade that adds a language is a red test and one command, never a fence that quietly stops
// being coloured.
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { bundledLanguages, bundledLanguagesInfo } from 'shiki/langs'
import shikiPackage from 'shiki/package.json' with { type: 'json' }

const OUT = join(import.meta.dir, '..', 'src', 'render', 'shiki-langs.ts')

/** The table exactly as `highlight.ts` built it before 2026-10-03: ids, then every alias on top. */
export function shikiTable(): Map<string, string> {
  const map = new Map<string, string>()
  for (const id of Object.keys(bundledLanguages)) map.set(id, id)
  for (const info of bundledLanguagesInfo) {
    map.set(info.id, info.id)
    for (const alias of info.aliases ?? []) map.set(alias, info.id)
  }
  return map
}

/** Space-separated words, wrapped as string concatenation a reader can scan. */
function wrapped(words: string[]): string {
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    if (line && line.length + word.length + 1 > 92) { lines.push(line); line = '' }
    line = line ? `${line} ${word}` : word
  }
  if (line) lines.push(line)
  return lines.map((l, i) => `  '${l}${i < lines.length - 1 ? ' ' : ''}'`).join(' +\n')
}

if (import.meta.main) {
  const table = shikiTable()
  const ids = [...table].filter(([k, v]) => k === v).map(([k]) => k).sort()
  const aliases = [...table].filter(([k, v]) => k !== v).map(([k, v]) => `${k}=${v}`).sort()
  writeFileSync(OUT, `// GENERATED by \`bun scripts/gen-shiki-langs.ts\` from Shiki ${shikiPackage.version}. Do not edit by hand:
// \`shiki-langs.test.ts\` fails the day this and Shiki's own table disagree, and names the script.
//
// Every spelling a fence may use, mapped to the ONE id its grammar is filed under. A copy rather
// than an import because the import carried every grammar with it into the Cloudflare build; the
// reason is at the top of the script.

/** Every grammar id (${ids.length}). */
const IDS =
${wrapped(ids)}

/** Every other spelling, \`alias=id\` (${aliases.length}). */
const ALIASES =
${wrapped(aliases)}

/** Shiki's spellings, ids and aliases alike, to the id their grammar is filed under. */
export const SHIKI_LANGS: ReadonlyMap<string, string> = new Map([
  ...IDS.split(' ').map((id): [string, string] => [id, id]),
  ...ALIASES.split(' ').map((pair): [string, string] => {
    const at = pair.indexOf('=')
    return [pair.slice(0, at), pair.slice(at + 1)]
  }),
])
`)
  console.log(`src/render/shiki-langs.ts: ${ids.length} ids, ${aliases.length} aliases (Shiki ${shikiPackage.version})`)
}
