// The rail: the listing sidebar and a post's table of contents, which are one piece of
// furniture wearing two sets of contents.
//
// Split out of `public.css.ts` on 2026-08-02, which had reached 400 lines exactly - one line
// from failing its own guard, so the next person to touch it for any reason would have been
// blocked by a check about something they were not thinking about. Same move that produced
// `prose.css.ts` and `utility.css.ts`.
//
// NO BACKTICKS ANYWHERE BELOW: the whole sheet is one template literal and a backtick inside
// a prose comment ends it, which turns the rest of the CSS into TypeScript. `check:css-literal`
// discovers this file by scanning the directory, so it was covered the moment it existed -
// which is the point of that check no longer keeping a hand-written list.
//
// It is concatenated in the SAME position it occupied inside BASE_CSS. Order is load-bearing
// here: several later rules win on a specificity tie alone.

export const RAIL_CSS = `
/* THE RAIL: the listing sidebar and the post's table of contents, which are one piece of
   furniture wearing two sets of contents. All server-rendered, so these rules apply with
   or without JavaScript; only the aria-current highlight and the mobile drawer come from
   the bundle.

   BELOW the rail breakpoint it sits above the article, in normal flow, exactly as written
   here. ABOVE it, the rules generated by singleRailCss move it into the left gutter. The
   frozen tree also had a slide-out drawer and a toggle island for narrow screens; a list
   that simply sits above the article needs neither, so that island is not ported. */
:root{--rail-w:250px;--rail-gap:40px;
  /* Gap between a rail row's text and the accent marker beside it. */
  --rail-pad:14px;
  /* Space between the header and the first line of content. The rail's top matches it, so
     the rail's first line is level with the article's first line. */
  --rail-top:3rem}

/* Mobile FIRST: the rail is a slide-out drawer opened from the header menu button. The
   injected geometry promotes it into the gutter above the breakpoint. ONE piece of DOM
   serves both, which is why there is no second copy of the sidebar to keep in step. */
/* overflow-x is spelled out, and it is not decoration. A box with overflow-y:auto and no
   overflow-x computes overflow-x to auto as well, so the drawer became a horizontal
   scroller the moment anything inside it was a pixel too wide - which is how a gutter rule
   meant for the desktop rail taught every phone to pan the sidebar 32px sideways. */
.rail{position:fixed;top:0;bottom:0;left:0;z-index:40;width:min(300px,84vw);
  overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;padding:4.5rem 1.25rem 2rem;
  background:var(--c-bg);border-right:1px solid var(--c-rule);
  transform:translateX(-100%);transition:transform var(--dur-base) ease}
html[data-rail=open] .rail{transform:none}
/* Two-rail listings only: on mobile there is no gutter, so the LEFT rail is hidden and its
   blocks appear in the right rail's drawer through .drawer-only. */
.rail-left{display:none}
/* Tap anywhere else to close. No dim: the drawer already owns a solid surface. */
.rail-scrim{position:fixed;inset:0;z-index:39}
.rail-inner{position:sticky;top:2.5rem}
.rail-inner > * + *,.drawer-only > * + *{margin-top:1.75rem}
.rail h2{margin:0 0 .75rem;padding-left:var(--rail-pad);font-weight:var(--fw-heading,600);color:var(--c-heading);
  font-size:var(--fs-small);line-height:var(--lh-small);
  letter-spacing:var(--ls-small)}
.rail ul{list-style:none;margin:0;padding:0}
.rail li{margin-top:.5rem}
.rail li:first-child{margin-top:0}
.rail-row{position:relative;display:flex;justify-content:space-between;gap:.875rem;
  padding-left:var(--rail-pad);color:var(--c-meta)}
.rail-row:hover,.rail-tags a:hover{color:var(--c-heading)}
/* The one accent mark: a hairline beside the row you are already reading. In the drawer it
   sits left of the text; in the gutter the rail flips and it faces the divider. */
/* ::after, not ::before. A row can be BOTH aria-current and .rail-lead (the bullet) or
   .rail-sub (the IDE chrome's leading slash), and all of them wanted the SAME
   pseudo-element: the marker's empty content won, and the slash came out painted in the
   accent colour as a red diagonal at the row's right edge. Two marks, two elements. */
.rail-row[aria-current]::after{content:"";position:absolute;left:0;top:3px;bottom:3px;
  width:2px;background:var(--c-accent)}
/* Counts sit in their own right-aligned column so the labels stay aligned however many
   digits a count carries. The column is exactly as wide as the widest count on the page
   (--count-w, in ch, exact because the digits are tabular); a fixed em width would leave
   dead space on every single-digit row. */
.rail-count{min-width:var(--count-w,1ch);text-align:right;flex-shrink:0;
  font-variant-numeric:tabular-nums}
.rail-tags{display:flex;flex-wrap:wrap;column-gap:.75rem;row-gap:.25rem;padding-left:var(--rail-pad)}
.rail-tags a{color:var(--c-meta)}
/* Tags are many and short: a wrapped run of plain words, no chips, no boxes. */
.rail-tags.lower a{text-transform:lowercase}
/* The brackets are CSS, not markup, so the IDE chrome can swap them for square ones and
   switching it off puts them back. They used to be typed into the sidebar renderer, which
   is why the taxonomy read "(7)" while the list beside it read "[7]". */
/* No opacity. --c-meta is 4.56:1 against the page and passes AA with 0.06 to spare; at .6
   the count measured 2.26:1, which is a fail at any size. It only ever looked acceptable
   because the IDE chrome resets the opacity to 1, so the site the owner sees was never the
   one shipping the failure: switching that off produced unreadable counts. */
.term-count{margin-left:.25rem;font-variant-numeric:tabular-nums}
.term-count::before{content:"("}
.term-count::after{content:")"}
.rail-row.is-active,.rail-tags a.is-active{font-weight:500;color:var(--c-heading)}
.rail-tags a.is-active{text-decoration:underline;text-decoration-color:var(--c-accent);
  text-underline-offset:4px}
/* No panel: no border, no shadow, no background, just type sitting on the page. It had a
   left border and a padded box, which read as a widget parked beside the article.

   Nest visually ONLY when the post MIXES levels: an H2 row carries one bigger dot as a
   section marker and an H3 row simply goes smaller. So it reads as a few strong markers
   over quieter children rather than a column of identical bullets. The dot is an inline
   ::before, so it flows for BOTH rail orientations with no per-side handling. */
.rail-lead::before{content:"•";font-size:.72em;margin-inline-end:.5em;vertical-align:.12em;
  color:var(--c-meta)}
.rail-sub{font-size:var(--fs-caption);line-height:var(--lh-caption);
  letter-spacing:var(--ls-caption)}
.toc-end{margin-top:1rem}
/* Below the rail breakpoint the ToC is the drawer, and a post with a long index needs the
   whole column: the listing rail is not on this page to share it with. */
.toc li{margin-top:.5rem}
`.trim()
